In [2]:
import pandas as pd

In [14]:
data = pd.read_csv(
    "./data/global_wordfreq.release_UTF-8.txt", sep="\t", header=None
).rename(
    columns={0:"char", 1:"freq"}
)

In [15]:
data

           char        freq
0             第  2002074595
1             的   943370349
2             了   255733044
3             在   197672850
4             是   171296602
...         ...         ...
1048571    赤崖堡村          25
1048572      经军          25
1048573     于松如          25
1048574  11．86％          25
1048575     胡良成          25

[1048576 rows x 2 columns]

In [12]:
data.rename(columns={0:"char", 1:"freq"})

           char        freq
0             第  2002074595
1             的   943370349
2             了   255733044
3             在   197672850
4             是   171296602
...         ...         ...
1048571    赤崖堡村          25
1048572      经军          25
1048573     于松如          25
1048574  11．86％          25
1048575     胡良成          25

[1048576 rows x 2 columns]